### PR TITLE
Fulltext simple search

### PR DESCRIPTION
**Pull request by FCRodriguez7**
**Story**

In FindIt there is descriptive text for the full text search option that displays in a popup when hovering over the "what's this?" text:

In Blacklight we'd like to display a similar message:
```
Search full text that occurs in a work. Not all works contain searchable full text.
```

**Acceptance**
Display the message:
- [ ] In the simple search, when "full text" is selected in the drop down, display the message under the text input for the search.

### CODE REVIEW

**Review by martinlovell — CHANGES_REQUESTED** [review]
Looks good.  A couple things: 
- I think this swaps the order in the simple dropdown so that fulltext come before orbis ID.  It's supposed to be the last option in the dropdown.
- It seems like the text should disappear when you change the dropdown to something other than fulltext.

**Comment by MaggieZhaoYale** [comment]
Screen Shot 2021-06-17 at 9 13 42 AM

**Comment by FCRodriguez7** [comment]
The last commit puts the order back.

**Comment by MaggieZhaoYale** [comment]
@martinlovell Thank you. Now the fulltext is the last in the dropdown, and the description disappears if change to other search fields.

**Comment by MaggieZhaoYale** [comment]
https://user-images.githubusercontent.com/46331329/122566459-8f2e5100-d015-11eb-9209-900148e5d1f8.mov

**Review by martinlovell — APPROVED** [review]

**Pull request merged**
