### PR TITLE
Remove excess whitespace in Safari

### PR DESCRIPTION
**Pull request by FCRodriguez7**
In Safari, there is excess whitespace between the title and the metadata on the search results screen

- [x] The whitespace between the header and the metadata in the search results screen should look the same as it does in firefox and chrome

### CODE REVIEW

**Comment by FCRodriguez7** [comment]
The correct changes were added to the css.  Safari looks identical to both Firefox and Chrome.  

Screen Shot 2020-08-12 at 10 48 43 AM

**Comment by FCRodriguez7** [comment]
The changes in the PR correct the excessive whitespace.

**Comment by alishaevn** [comment]
Both of the issues below are happening in Chrome and Safari.

The light grey border that separates each item from the next is showing in the middle of the first item instead of after it. it displays correctly after the second item though.
image

The text overlaps when the page is smaller
image

**Comment by FCRodriguez7** [comment]
The commit "ed0f6ad" fixed the text overlap/bleeding.   

Screen Shot 2020-08-13 at 10 49 01 AM

**Comment by FCRodriguez7** [comment]
Screenshots for large and medium screen sizes: 
 

LARGE 
Screen Shot 2020-08-13 at 12 15 33 PM
----
MEDIUM
Screen Shot 2020-08-13 at 12 04 43 PM

**Pull request merged**
