### PR TITLE
Search Bar Alignment and Sizing

### PR DESCRIPTION
**Pull request by alishaevn**
# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/589

# Expected behavior
- the "advanced search" button has the correct font
- deleted the "advanced search" style file and added the style to the "search bar" style file because it's part of the search bar
- removed the hover and active states for the "search" button
- edited the responsiveness from 375px wide and larger
- on devices <= 767px wide, the search bar is broken into 3 rows
    - the drop down is full width
    - the input field is full width underneath is
    - the "search" and "advanced search" buttons are inline and underneath the input field
- on devices >= 767px wide, the search bar is in a single row and centered

# Demo

### CODE REVIEW

**Comment by alishaevn** [comment]
@FCRodriguez7 I've created this as a draft for now because of the acceptance criteria:
```
The font size should be smaller across that area
  *Please refer to the Zeplin board
```
The zeplin board shows that the font size for all of the text in the search bar should be 20px. although the `height` (not to be confused with `line-height`) is 16px for some reason. I've set the font size to be 20px. are you saying that it should be something else?

if matt would like for us to make things different sizes that what the design document shows...can you please ask him to notate that in each of the areas where something should be different?
image

**Review by FCRodriguez7 — CHANGES_REQUESTED** [review]
The PR seems to increase the font size for the advanced search button only.  I worked on this button with Matt and received this approval.  Could we leave it at the original size font and not newly changed sized?

**Comment by alishaevn** [comment]
> The PR seems to increase the font size for the advanced search button only. I worked on this button with Matt and received this approval. Could we leave it at the original size font and not newly changed sized?

I can do that, but if that's the case, all of the font sizes should be changed for consistency and not just the one.

**Comment by alishaevn** [comment]
@FCRodriguez7 done

**Review by FCRodriguez7 — APPROVED** [review]

**Pull request merged**
