### PR TITLE
Add yale assets

### PR DESCRIPTION
**Pull request by K8Sewell**
# Summary 
Adds Yale specific color palette as variables.  Includes social icons in the asset pipeline.  

# Screenshots
### Home Page
* Updated header background to Yale Blue
<details>
image
</details>

### Icons & Logo Included
* Mail, Facebook, Twitter, Instagram, YUL Logo, Music Thumbnail, X, and checkboxes
<details>
image
image
image
image
</details>

### CODE REVIEW

**Comment by alishaevn** [comment]
> Do not merge until we have a clear answer on whether we're allowed to put this font in a public github repo.

@bess we're using a url for the typeface now. plus some other hierarchal changes. 🙂

**Comment by alishaevn** [comment]
@bess Also....the coverage shows it decreased by 0.3%....which makes sense because we added lines without specs. but you don't write specs for tests. so I imagine as we continue styling, the overall repo coverage will decrease since we are strictly doing line coverage.

**Comment by bess** [comment]
@alishaevn This looks great, and the drop in coverage is no problem, for exactly the reasons you mention. Would you please squash these commits though (or open a new PR from a new branch... whatever is easier) so the font additions don't end up anywhere in the commit history? Also, could we add some screen shots of what the application looks like with these additions, both to the PR and to the ticket? Thanks, and great work!

**Comment by alishaevn** [comment]
Closing in favor of https://github.com/yalelibrary/yul-dc-blacklight/pull/168.

**Pull request closed without merging**
